%function from comFramework used to import the DBC information
%Note, dbcParserForOctave.stg is needed and is a templete for how the DBC file will be imported into Octave

function dbcFile = dbcParser(dbcFileName, nodeName)
% Parse CAN network database dbcFileName and return the parse result.
% nodeName: The name of the ECU. Needed to determine the send direction.
    tmpFileName = tempname;
    templateGroupFileName = 'dbcParserForOctave.stg';
    cmd =                                                      ...
    [ 'codeGenerator'                                          ...
      '  --cluster-name Octave'                                ...
      '  --node-name ' nodeName                                ...
      '  --bus-name bus'                                       ...
      '  -dbc ' dbcFileName                                    ...
      '  --output-file-name ' tmpFileName                      ...
      '    --template-file-name ' which(templateGroupFileName) ...
    ];
    % Run the comFramework code generator as an external tool.
    system(cmd);
    % run will create object dbcFile in the function's workspace.
    run(tmpFileName);
    % The parse result as a *.m file is no longer required.
    delete(tmpFileName);
end % dbcParser
